name: Build and Push Container to GitHub Container Registry

on:
  push:
    branches:
      - no-aws

jobs:
  build_and_push:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build and Push Container to ghcr.io
        uses: GlueOps/github-actions-build-push-containers@v0.3.7